### ISSUE TITLE
Workshop schedule

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/2021-07-19-cms-open-data-workshop#4]
Define and implement workshop schedule

**Comment by katilp** [comment]
For the record, that's what we have last year: https://cms-opendata-workshop.github.io/2020-09-30-cms-open-data-workshop-for-theorists/#schedule
For the lecturers/tutors from the Americas, we should mostly schedule lectures and demos for the CERN afternoon, although if needed schedule-wise, I would not totally exclude CERN mornings either.

In general, should we indicate in the agenda "Hands-on work-on-your-own" time for CERN morning and US afternoon?
Did you have the impression that the participants were able to work through the exercises during the lecture/demo slots, or did they do them after on their own?

**Comment by caredg** [comment]
I got the feeling that the lessons, in general, would go better if we get the time to work with them as we progress along during the tutorials, let them work by themselves, and then show the answer..... Then maybe leave some *related* challenges so they can work on that on their own time.

**Comment by katilp** [comment]
OK, that would then speak for a structure like "Intro/demo" N mins, "Hands-on time"  N*2 min, "Solution" N/2 mins, or something similar for all topics requiring coding. Would that work or would it become too scattered?

**Comment by mattbellis** [comment]
I think that would work actually. I think we just want to put some thought into how we schedule which lesson when, based on the feedback. There were a number of comments about missing the overall big picture and flow of an analysis. Once we revisit that, I think the structure you suggest "Intro --> hands-on --> solution/debrief" is a good one.
